version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ideasoft-php-app
    container_name: ideasoft_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    expose:
      - "9000"
    depends_on:
      - mysql
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=ideasoft
      - DB_USERNAME=root
      - DB_PASSWORD=root
  nginx:
    image: nginx:alpine
    container_name: ideasoft_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  mysql:
    image: mysql:8.0
    container_name: ideasoft_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ideasoft
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
volumes:
  db_data:
